export enum StorageVariable {
  ONBOARDING_TOKEN = "hbko-onbtkn",
  ACCESS_TOKENS = "hbko-a-cts",
  REFRESH_TOKENS = "hbko-r-cks",
  TOKEN_EXPIRY = "hbko-tksexp",
  IS_AUTHENTICATED = "at-auht",
  USER_DATA = "us-dnfo",
  USER_EMAIL = "hbko-umal",
  DRIVERS = "hbko-apts",
  SEARCH_QUERIES = "hbko-srh-q",
  AUTH_DATA = "hbko-aud",
  LOGGED_IN_USER_DATA = "hbko-liud",
  SUPER_ADMIN = "hbko-sdm",
  USER_ID = "hbko-u1",
  USER_TYPE = "hbko-uty",
  ACCESS_TOKEN_EXPIRY = "ACCESS_TOKEN_EXPIRY",
  SIGNUP_CONFIRMATION_TOKEN = "sup-cftkn",
  PASSWORD_RESET_TOKEN = "ft-pwdrst-tkn",
}
